### PR TITLE
Should work now on win64

### PR DESCRIPTION
**Pull request by YoelShoshan**
Tested only on win64, should work on win32 and linux as well

### CODE REVIEW

**Comment by bastibe** [comment]
I already merged the README changes in the other pull request, and now cherry-picked only the changes to the header. As always, thank you very much for your contributions!

**Comment by YoelShoshan** [comment]
No problem!
Notice that this has few MORE readme changes, which I think that are kinda important.
The part that I (mistakenly) called WINDOWS INSTALLATION GUIDE is more of a trouble shoot for windows. Also added some important tip about the interactive matlab session window (which is actually my only indication if the loadlibrary stuff are well configured).
In the case that it's NOT well configured, transplant just hangs + the matlab window is interactive.

Your call - just be aware of the extra info in the readme :)

**Comment by bastibe** [comment]
Oh, I'm sorry. I'll incorporate that soon, then!

**Comment by bastibe** [comment]
I think this has all been merged.

**Pull request closed without merging**
