### PR TITLE
Make sure license and other files are properly in sdist

### PR DESCRIPTION
**Pull request by toddrme2178**
Fixes a bug that prevents critical files like the license from being in the sdist.

### CODE REVIEW

**Comment by toddrme2178** [comment]
While you are preparing a new release, would it be possible to create a tag for the latest release (0.8.10)?  I want to manually include the LICENSE file from github, but I need a tag in order to do that.

**Comment by bastibe** [comment]
I am not familiar with the Manifest file. Could you point me to the relevant documentation?

**Comment by bastibe** [comment]
I tagged the latest release. Is this satisfactory?

**Comment by toddrme2178** [comment]
@bastibe [Here](https://docs.python.org/distutils/sourcedist.html) is some basic information on MANIFEST.in files.

**Comment by toddrme2178** [comment]
Thanks, that will work for now but having the license in sdists is required by the license terms.

**Comment by bastibe** [comment]
Cool, thank you!

**Comment by bastibe** [comment]
However, I'm on vacation right now, and won't be able to push a new sdist to PyPi until September.

**Pull request merged**
